<a href="https://colab.research.google.com/github/abrarzayedgithub/tensorflow/blob/main/introduction_to_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [4]:
rank_2_tensor = tf.constant([[1,2],[2,1],[3,1]],dtype = tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [2. 1.]
 [3. 1.]], shape=(3, 2), dtype=float16)


In [5]:
np.array(rank_2_tensor)

array([[1., 2.],
       [2., 1.],
       [3., 1.]], dtype=float16)

In [6]:
rank_3_tensor = tf.constant([
                                [[1,2,3,4,5],
                                 [2,2,3,4,4]],
                                [[1,2,3,4,5],
                                 [6,2,5,2,3]],
                                [[5,2,6,3,9],
                                 [9,4,2,4,7]],])
print(rank_3_tensor)



tf.Tensor(
[[[1 2 3 4 5]
  [2 2 3 4 4]]

 [[1 2 3 4 5]
  [6 2 5 2 3]]

 [[5 2 6 3 9]
  [9 4 2 4 7]]], shape=(3, 2, 5), dtype=int32)


In [7]:
a = tf.constant([[1,2],
                 [2,1]])
b = tf.constant([[2,2],
                 [4,5]])
print(tf.add(a,b),'\n')
print(tf.multiply(a,b),'\n')
print(tf.matmul(a,b),'\n')

tf.Tensor(
[[3 4]
 [6 6]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[2 4]
 [8 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[10 12]
 [ 8  9]], shape=(2, 2), dtype=int32) 



In [8]:
c = tf.constant([[4.0,5.0],[10.0,1.0]])
#find the largest value
print(tf.reduce_max(c))
#find the index of the largest value
print(tf.math.argmax(c))
#compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [9]:
rank_4_tensor = tf.zeros([3,2,4,5])
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [10]:
print("type of every element:",rank_4_tensor.dtype)
print("number of axes:", rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("element along axis 0 of tensor",rank_4_tensor.shape[0])
print("element along the last axis of tensor:",rank_4_tensor.shape[-1])
print("total number of element(3*2*4*5):",tf.size(rank_4_tensor).numpy())

type of every element: <dtype: 'float32'>
number of axes: 4
shape of tensor: (3, 2, 4, 5)
element along axis 0 of tensor 3
element along the last axis of tensor: 5
total number of element(3*2*4*5): 120


In [11]:
rank_1_tensor = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(rank_1_tensor.numpy())
print(rank_1_tensor)

[0 1 2 3 4 5 6 7 8 9]
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [12]:
print("first:",rank_1_tensor[0].numpy())
print("second:",rank_1_tensor[1].numpy())
print("second:",rank_1_tensor[-1].numpy())

first: 0
second: 1
second: 9


**manipulating shapes **


In [13]:
x = tf.constant([[1],[2],[3]])
print(x.shape)

(3, 1)


In [14]:
print(x.shape.as_list)

<bound method TensorShape.as_list of TensorShape([3, 1])>


In [15]:
reshape = tf.reshape(x,[1,3])
print(x.shape)
print(reshape.shape)

(3, 1)
(1, 3)


In [16]:
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3 4 5]
  [2 2 3 4 4]]

 [[1 2 3 4 5]
  [6 2 5 2 3]]

 [[5 2 6 3 9]
  [9 4 2 4 7]]], shape=(3, 2, 5), dtype=int32)


# A `-1` passed in the `shape` argument says "Whatever fits".

In [17]:
print(tf.reshape(rank_3_tensor,[-1]))

tf.Tensor([1 2 3 4 5 2 2 3 4 4 1 2 3 4 5 6 2 5 2 3 5 2 6 3 9 9 4 2 4 7], shape=(30,), dtype=int32)


In [18]:
print(tf.reshape(rank_3_tensor,[6,5]))
print(tf.reshape(rank_3_tensor,[3,-1]))

tf.Tensor(
[[1 2 3 4 5]
 [2 2 3 4 4]
 [1 2 3 4 5]
 [6 2 5 2 3]
 [5 2 6 3 9]
 [9 4 2 4 7]], shape=(6, 5), dtype=int32)
tf.Tensor(
[[1 2 3 4 5 2 2 3 4 4]
 [1 2 3 4 5 6 2 5 2 3]
 [5 2 6 3 9 9 4 2 4 7]], shape=(3, 10), dtype=int32)


In [19]:
print(tf.reshape(rank_3_tensor,[2,3,5]))
print(tf.reshape(rank_3_tensor,[5,6]))
print(tf.reshape(rank_3_tensor,[7,-1]))

tf.Tensor(
[[[1 2 3 4 5]
  [2 2 3 4 4]
  [1 2 3 4 5]]

 [[6 2 5 2 3]
  [5 2 6 3 9]
  [9 4 2 4 7]]], shape=(2, 3, 5), dtype=int32)
tf.Tensor(
[[1 2 3 4 5 2]
 [2 3 4 4 1 2]
 [3 4 5 6 2 5]
 [2 3 5 2 6 3]
 [9 9 4 2 4 7]], shape=(5, 6), dtype=int32)


InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:GPU:0}} Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]

**Broadcasting**


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([2,3,4])
print(tf.multiply(x,2))
print(x*y)
print(x*z)

In [ ]:
x = tf.reshape(x,[3,1])
y = tf.range(1,5)
print(x,'\n')
print(y,'\n')
print(tf.multiply(x,y))

In [ ]:
x_stretch = tf.constant([[1,1,1,1],
                         [2,2,2,2],
                         [3,3,3,3]])
y_stretch = tf.constant([[1,2,3,4],
                         [1,2,3,4],
                         [1,2,3,4]])
print(x_stretch*y_stretch)

**ragged tensor**

In [ ]:
ragged_list = [[0,1,2,3],
               [4,5],
               [6,7,8],
               [9]]
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

In [22]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


**string tensor **

In [23]:
scalar_string_tensor = tf.constant('gray wolf')
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)


In [24]:
tensor_of_string = tf.constant(['gray wolf',
                                 'tiger',
                                 'cat'])
print(tensor_of_string)

tf.Tensor([b'gray wolf' b'tiger' b'cat'], shape=(3,), dtype=string)


In [25]:
print(tf.strings.split(scalar_string_tensor,sep = ''))

tf.Tensor([b'gray' b'wolf'], shape=(2,), dtype=string)


In [26]:
print(tf.strings.split(tensor_of_string,sep = ' '))

<tf.RaggedTensor [[b'gray', b'wolf'], [b'tiger'], [b'cat']]>


In [30]:
text = tf.constant('1 10 100')
print(tf.cast(tf.strings.to_number(tf.strings.split(text,sep = ' ')),dtype = tf.uint8))

tf.Tensor([  1  10 100], shape=(3,), dtype=uint8)


In [33]:
byte_string = tf.strings.bytes_split(tf.constant('wolf'))
print('byte_string',byte_string)

byte_string tf.Tensor([b'w' b'o' b'l' b'f'], shape=(4,), dtype=string)


**sparse tensor**

In [36]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0,0],[1,2]],
                                       values = [1,2],
                                       dense_shape = [3,4])
print(sparse_tensor,'\n')

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

